### PR TITLE
[orga] fix organiser creation, closes #508

### LINKED ISSUE #508: cannot create organiser
## Expected Behavior

As an admin, I'd like to create new organizers.

## Current Behavior

image

## Steps to Reproduce

1. go to `/orga/organiser/new`
2. enter data into all non-disabled fields
3. press save
4. receive "This field is required." for the short form, which is disabled

## Your Environment

* Version used: v0.8.0
* Environment name and version (e.g. Chrome 39, python 3.5): N/A
* Operating System and version (desktop or mobile): N/A
* Link to your instance, if in production: conference.c3w.at

### PR DESCRIPTION
**Pull request by luto**
fix #508 

## How Has This Been Tested?

using the supplied test.. :)

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [ ] My change is listed in the CHANGELOG.rst if appropriate.

### CODE REVIEW

**Comment by luto** [comment]
while this fixes the form, it allows any user with the `can_change_organiser_settings` flag to create new organizers. I don't see any permission, which could be used for this from.. soo maybe a new one just checking for `is_administrator`?

**Comment by rixx** [comment]
Yeah, making this an administrator-restricted action would be best.

**Comment by luto** [comment]
I've adapted the permission check and added a couple of tests. Have a look, please :)

**Comment by luto** [comment]
turns out, the code was correct already. I've removed my changes but left the tests in place m)

**Pull request merged**
