### PR TITLE
Validate pretalx frab json exports with VOC schema

### PR DESCRIPTION
**Pull request by rixx**
Continuing the conversation at #1334: VOC has a JSON schema that we can use to comply against a shared set of expectations, instead of being surprised by frab changes.

Currently waiting for changes in the JSON schema.

### CODE REVIEW

**Comment by saerdnaer** [comment]
Sorry for the delay, the JSON schema now allows `UTC` as valid time zone name (and regex had another bug, too) – Thanks for pointing me to that issue!

**Comment by rixx** [comment]
No worries, it's not like it's urgent – thanks for pushing this forward!

It seems the remaining failing check is for `room.guid`, which the schema expects to be present, but which is currently optional in pretalx, iirc for backwards compatibility reasons. No strong preference what to do here (though adding required room guids to pretalx requires writing three db migrations and I'm lazy …).

**Comment by rixx** [comment]
It seems that the VOC schema currently requires room GUIDs, while these are an optional feature in pretalx.

At this point, I'm once again thinking about moving all the frab/VOC exports to a separate plugin, and that plugin could also be responsible for generating room GUIDs where necessary. Maintaining this in pretalx-core is looking increasingly like a maintenance burden due to lack of standardisation etc.

**Comment by saerdnaer** [comment]
I would provide an seperate PR which generates the room guid from the pretalx domain name and the internal room id in the database – this should resolve the issues we had with the integration tests with the previous random based room guids.

**Comment by rixx** [comment]
Sure! I'll consider this PR dormant until then.

**Comment by saerdnaer** [comment]
@rixx When you update the JSON Schema from the source, this tests should become green now.

**Comment by rixx** [comment]
You'll probably want to rebase this PR (and fix the merge conflict) to see if tests are passing now.

**Comment by Kunsi** [comment]
This branch is in the official `pretalx` organization, i cannot rebase this because i lack committer access.

**Comment by rixx** [comment]
> This branch is in the official `pretalx` organization, i cannot rebase this because i lack committer access.

Ah yeah, I somehow grouped this mentally under all the other VOC PRs (though in any case, I was addressing saerdnaer incorrectly, didn't mean to make you do anything!)

**Comment by rixx** [comment]
> When you update the JSON Schema from the origin, this tests should become green now.

Nope. pretalx is returning a null-value for room GUIDs, whereas your change made the GUID field optional – so jsonschema correctly fails, because `None` is not a string value, which is intended for `room.guid`. Still blocked on either merging the room.guid feature branch or pulling all frab compatibility into a separate plugin, depending on what happens first.

**Pull request merged**
