### PR TITLE
Review phases

### PR DESCRIPTION
**Pull request by rixx**
This PR closes/references issue #611, as detailed in the proposal in that issue. Todo:

- [x] Add review phase model
- [x] Migrate existing settings to review phase model
- [x] Create sensible review phase for exsting events
- [x] Create better review phases for new events
- [x] Update review phase via regular cronjob
- [x] Provide interface for review phase CRUD
- [x] Implement activation and ordering
- [x] Implement new review permissions in all pages

### CODE REVIEW

**Comment by vmx** [comment]
> * Provide interface for review phase CRUD + ordering

What is the ordering about? I'm asking as I have a special request about the ordering, I didn't bring up yet as I thought it could be done later, but now it might make sense to bring it up.

I'd like to have a custom ordering per reviewer. So that the ordering is the same every time a reviewers looks through the submissions, but the ordering is different between different reviewers.

The reason for this is for conferences where not all reviewers review all submissions. This way the each reviewer can start at their top and if they do enough reviews, eventually everything will get reviewed. This might also lower bias, as you might score proposals differently at the beginning or the end of the list.

I know that this doesn't work well with paging/Django's ORM. You would need to get the full list and sort it manually. But I think it would be great having this as an option with a warning that it might slow down the system.

**Comment by rixx** [comment]
> I'd like to have a custom ordering per reviewer. So that the ordering is the same every time a reviewers looks through the submissions, but the ordering is different between different reviewers.

This is a) out of scope for this MR, and b) not going to happen in pretalx any time soon. Stable random ordering is horrible to mix with pagination, and it wouldn't be worth the effort, I feel. Reviewers can go with the "save and next" functionality which gives them a random not-yet-reviewed submission, so we have random ordering, but don't have to deal with the combination of stable per-user randomness.

**Comment by vmx** [comment]
> This is a) out of scope for this MR,
I agree it is out of scope I just wanted to bring it up in case it interferes with the current work (which is does not).

> Stable random ordering is horrible to mix with pagination, and it wouldn't be worth the effort, I feel.

Stable random sort works with pagination (at least in my tests), it's more of a performance/load issue.

> Reviewers can go with the "save and next" functionality which gives them a random not-yet-reviewed submission

Oh, wow. I thought "next" means "next in the list". That's great and solves my problem.

**Comment by rixx** [comment]
> Stable random sort works with pagination (at least in my tests), it's more of a performance/load issue.

Oh, cool! So what method did you use to achieve stable random sorting? I'm not aware of any one that works with SQLite (and I'm not ready to drop SQLite support for pretalx).

**Comment by vmx** [comment]
> Oh, cool! So what method did you use to achieve stable random sorting? I'm not aware of any one that works with SQLite (and I'm not ready to drop SQLite support for pretalx).

What I meant with performance/load issues is that you need to query the full table (without pagination). Convert that into an array. You then do the stable random sorting on it and return that result instead of the queryset. Django will take care of the pagination automatically.

**Comment by rixx** [comment]
> What I meant with performance/load issues is that you need to query the full table (without pagination).

I'd judge this to be inacceptable in terms of performance – I'm using pagination precisely to reduce wait times and load. Once we've pulled everything from the db, we might as well stop using pagination at all. Some databases can do seeded random sorting, but as I said: to me, it's not at all worth the effort.

The only way of achieving this that I'd accept would be to provide stable random sorting only if pretalx runs with the appropriate databases. I'd probably merge a MR providing this, but I'll definitely not tackle it myself unless as sponsored development.

**Pull request merged**
