### PR TITLE
Clarify what 'talk image' is

### PR DESCRIPTION
**Pull request by benjaoming**
## How Has This Been Tested?

This contains string changes, so will need translation of course.

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] My change is listed in the CHANGELOG.rst if appropriate.

### CODE REVIEW

**Comment by rixx** [comment]
Apart from the fact that the link is missing – it's not true that this is typically a profile picture of the speaker, that's what the speaker image is there for. Talk images *can* be speaker images, but can also illustrate some point the talk makes.

**Comment by benjaoming** [comment]
Oh, the link got truncated. Here: https://twitter.com/Hamatti/status/1075728846291386369

**Comment by benjaoming** [comment]
So was wondering what a or clearer instruction could be?

_Use this in case you want a special illustration to go with your talk. Leave empty if you intend to add a profile picture of yourself to your profile later._

**Comment by MaZderMind** [comment]
@benjaoming How about a more explanatory form of your suggestion: _A picture or illustration representing the topic of your talk._

**Comment by benjaoming** [comment]
@MaZderMind hmm, but the original confusion was that people would add a picture of themselves, so I would think it's better to be explicit about that this is *not* what the upload field is for? They haven't seen how to add a profile picture when they first see this field.

**Comment by rixx** [comment]
I'd like to keep this statement positive, and I think positive examples are a better way to go than negative exclusions.

**Comment by benjaoming** [comment]
> _Use this in case you want a special illustration to go with your talk. Leave empty if you intend to add a profile picture of yourself to your profile later._

**Comment by rixx** [comment]
I added a help text to the field, thank you for bringing this to my attention!

**Pull request closed without merging**
