### PR TITLE
Add zh_TW locale support and translations

### PR DESCRIPTION
**Pull request by fweng322**
Add Traditional Chinese (zh_TW) locale support and translations

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] My change is listed in the CHANGELOG.rst if appropriate.

### CODE REVIEW

**Comment by rixx** [comment]
Sad to see this PR closed – anything I can do to help, apart from addressing #865?

**Comment by fweng322** [comment]
> Sad to see this PR closed – anything I can do to help, apart from addressing #865?

I just found two errors in django.po.  Sorry for making troubles.  I'll send PR again with correct files.

**Comment by rixx** [comment]
To avoid future conflicts (merge conflicts in translation files are honestly the worst!), I have set up better translation infrastructure. Once you are ready, you can add your new translation (which is super cool, btw, thank you!) to [translate.pretalx.com](https://translate.pretalx.com). It allows you to import .po files, so you can just take your existing work and upload it there.

Feel free to let me know if you run into any problems!

**Comment by fweng322** [comment]
I've created Traditional Chinese (zh-hant on weblate) and uploaded my translations.  Do I still have to send patch for settings.py?  I just added lagnuage setting (but I used zh_TW there).

**Comment by rixx** [comment]
I've merged your translation in #686! I made the necessary adjustments to `settings.py`, so this is how it will look to users: 
Screenshot_2020-01-29 Write the Docs Portland 2020 pretalx(1)

**Comment by fweng322** [comment]
Thank you very much.  I'll keep updating translations directly on weblate.

**Pull request closed without merging**
