### PR TITLE
docs: make sure the pretalx-worker is properly installed

### PR DESCRIPTION
**Pull request by kannes**
This makes using Celery not an optional "if you decide to" but, as the installation is otherwise not working out of the box, a requirement.

If this is actually optional and advanced users can use pretalx without, I would recommend splitting optional things into a separate document for those users.

This PR references issue https://github.com/pretalx/pretalx/issues/680

## How Has This Been Tested?
Not tested from scratch. Based on my installation on Ubuntu 18.04 today.

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] My change is listed in the CHANGELOG.rst if appropriate.

### CODE REVIEW

**Comment by rixx** [comment]
This is incorrect – it's perfectly valid and possible to run pretalx without celery worker processes (indeed, on the current release it was necessary to do in combination with Python 3.7 for a long time due to Celery's rather slow release cycle). I have several pretalx instances running in production without celery worker processes, and they are definitely capable of sending emails.

**Comment by kannes** [comment]
Then the existing docs would be wrong, they say (emphasis mine):

> If you decide to use Celery (giving you asynchronous execution for long-running tasks), you’ll also **need** a second service /etc/systemd/system/pretalx-worker.service with the following content:

**Comment by rixx** [comment]
Yes, that is correct – if you have a `celery` section in your configuration, pretalx will assume you have a task runner out there, and will defer all tasks to a celery queue. If celery is not configured, pretalx will not depend on a task runner. Celery (the library) is installed in any case, as it is a dependency of pretalx, but if it is not *configured*, it will not behave as a task runner, and all potentially async tasks are executed directly (blocking, sync) instead.

**Comment by kannes** [comment]
Then I proposed the following note at the end of https://docs.pretalx.org/en/latest/administrator/installation.html#step-4-configuration:

```
.. note:: The suggested configuration above includes a ``[celery]`` section.
          This means that you *do* use Celery if that comes up below.
```

Maybe with a link to https://pretalx.readthedocs.io/en/latest/administrator/configure.html#the-celery-section

No PR because I kept this all on GitHub for now and forks are icky once out-of-date.

**Comment by rixx** [comment]
As of c30b6067 you can see the current celery queue length in the new admin panel, which might help debugging.

**Comment by kannes** [comment]
That sounds like a great solution. I am super impressed by your work!

**Comment by rixx** [comment]
Thank you! And also thank you for your continued feedback – I'm sorry the last interactions were mostly me shutting down your ideas, but I'm definitely happy to hear your experiences and to figure out ways to make them better. (Just gotta keep the overall project direction in mind at the same time.)

**Comment by kannes** [comment]
Your replies were always clearly motivated by a strong vision how things *should* work, no need to feel sorry in any way!

**Pull request closed without merging**
