### PR TITLE
[WIP] Add links for objects in action logs for Submission and CfP

### PR DESCRIPTION
**Pull request by rahmonov**
Hey guys, does it look okay? Or did you have something else in mind?

### CODE REVIEW

**Comment by rahmonov** [comment]
@rixx does it look okay? or do we need something finer-grained? like for separate links for submission speakers, reviews and etc?

**Comment by rixx** [comment]
@rahmonov Apart from the failing code style tests, the only improvement I could think of would be separate methods to get an organiser area url and a public url – but that's something we could add later, aswell.

**Comment by rahmonov** [comment]
@rixx fixed the style issues. I feel stupid but could not figure out "separate methods to get an organiser area url and a public url" :) Can we create a separate issue for this with a little more description?

**Comment by rixx** [comment]
Sure, thank you very much!

**Pull request merged**
