### PR TITLE
🗺 Update French translation

### PR DESCRIPTION
**Pull request by sparunakian**
Hi,

This MR updates the French translation.

There is a message in English which doesn't seem relevant, regarding the new (neat) widget:
https://github.com/pretalx/pretalx/blob/5802c2ccf546cf8a9cb21bb8cf79e0cea8b389bd/src/pretalx/orga/templates/orga/settings/widget.html#L18

The "instead of using this page." part implies that the planning is displayed on this page, which is wrong. Shouldn't it be something like "instead of using the planning page in pretalx"? Or am I misunderstanding? In the French translation I've kept the same meaning as in English.

## How Has This Been Tested?

NA

## Screenshots (if appropriate):

NA

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] My change is listed in the CHANGELOG.rst if appropriate.

### CODE REVIEW

**Comment by rixx** [comment]
Thank you for the update! You are correct, the phrasing is a bit off on that widget information. I'll update it later on.

**Comment by sparunakian** [comment]
As always, thank *you* for pretalx :-) I'll update the MR after you edit the phrasing.

**Comment by rixx** [comment]
I'll merge the MR right now without waiting for the changed string (which I'll tackle later on): I'm trying to build proper translation infrastructure, which involves updating our translation files, and I really don't want to introduce merge conflicts on that scale.

Thank you as always – I'll ping back here once I know if proper translation ifnrastructure is feasible to set up!

**Comment by rixx** [comment]
Right, here we go: There is now [translate.pretalx.com](https://translate.pretalx.com), powered by weblate. This will make it a bit easier to work around merge conflicts (or so I hope) – it'll generate MRs against pretalx, and you can still work with local .po files and export/import them, if you prefer. I'll add documentation to pretalx (… tomorrow, though), but you can get started there now, if you'd like :)

**Comment by sparunakian** [comment]
[translate.pretalx.com](translate.pretalx.com) looks nice! I'm looking forward to use it. Thank you for the merge.

**Pull request merged**
