### PR TITLE
Always display speaker-image in the same size

### PR DESCRIPTION
**Pull request by MaZderMind**
The current CSS implementation around the Speaker's avatar is currently slightly sub-optimal. The actual with of the avatar-image is dependent on the original image-with as well as on the bio-text and how it is flowing/wrapped.

This results in a suboptimal and inconsistent presentation for some speakers:
vorher-1
vorher-2

Furthermore there is no visual space between the speaker's avatar and the Ical-button above it.

This PR changes the CSS for this place, ensuring a consistent width of the avatar-Image, adjusting the bio-text as required.

## How Has This Been Tested?
Setting the Image- and Bio-Texts from the two problematic cases listed above ([Reda Chatar](https://talks.seibert-media.net/summit19/speaker/HHLAUY/) and [Bastian Schmitt](https://talks.seibert-media.net/summit19/speaker/T9RQ3Q/)) results in the presented Effect in Chrome.

## Screenshots (if appropriate):
With this PR applied, the visual representation is consistent across all images and bio-texts and acceptable for all devices:
bildschirmfoto 2019-02-06 um 15 27 42
bildschirmfoto 2019-02-06 um 15 27 58
bildschirmfoto 2019-02-06 um 15 28 02
bildschirmfoto 2019-02-06 um 15 28 09
bildschirmfoto 2019-02-06 um 15 28 53
bildschirmfoto 2019-02-06 um 15 29 07
bildschirmfoto 2019-02-06 um 15 29 12
bildschirmfoto 2019-02-06 um 15 29 19

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] My change is listed in the CHANGELOG.rst if appropriate.

### CODE REVIEW

**Comment by rixx** [comment]
Thank you, this is a very welcome addition! If you're up for it, there are two things I'd like to consider:

- Now that we have a fixed size, it would be good to mention this in the ``help_text`` of the image field, to aid speakers in the image selection.
- The image looks better now, but it's still a bit misplaced, all on its own – adding either a border or some box-shadow might alleviate that.

I can take care of those points after a merge, or you can add them to your PR, as you prefer.

**Comment by MaZderMind** [comment]
@rixx Thank you for your feedback. I'll update the PR with those additions.

**Comment by MaZderMind** [comment]
Actually, the same Issue can be obI added the box-shadow and the requested help-text in all three places, where the avatar Form is used:
bildschirmfoto 2019-02-06 um 17 50 08

While I was at it, I noticed the misalignment of the form elements around the avatar-form in all three locations. I fixed them as well:
bildschirmfoto 2019-02-06 um 17 54 48

For the cfp Form this also included reworking the "orga edit" button, which was causing misalignment all around the cfp form:
bildschirmfoto 2019-02-06 um 19 26 31

this is fixed now as well:
bildschirmfoto 2019-02-06 um 19 33 32

**Comment by rixx** [comment]
I've merged this manually because GitHub's merge conflict resolution was being weird. Thank you very much! :cookie:

**Pull request closed without merging**
